version: "3.9" #version of the docker code that we are going to use

services:
  app:
    build:
      context: .
      args:
        - DEV=true #requirements.dev.txt
    ports:
      - "8000:8000" #port for local and container
    volumes:
      - ./app:/app #from ./app to container 
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"